### ISSUE TITLE
Breakpoint right after pydevd.settrace call

### ISSUE THREAD

**Issue by Bonjour123** [JesusFreke/fusionIdea#17] opened 2022-06-03 13:45 UTC
When I detach the debugger (with the stop button inside pycharm) and then attach it again (with the run/rerun button), Pycharm always brings up the following file ` PyCharm2022.1\plugins\fusion_idea\lib\pydevd-1.9.0\pydevd_attach_to_process\attach_script.py` 
 and breaks at the line 

` pydevd.settrace(
            port=port,
            host=host,
            stdoutToServer=True,
            stderrToServer=True,
            overwrite_prev_trace=True,
            suspend=False,
            trace_only_current_thread=False,
            patch_multiprocessing=False,
        )`

I though that the problem was related to the line right before it:
`        if py_db is not None:
            py_db.dispose_and_kill_all_pydevd_threads(wait=False)`

but I checked that `dispose_and_kill_all_pydevd_threads` is well defined, and changed `wait` to True. 
But  Pycharm still breaks right after the `pydevd.settrace` call

Also, it seems this issue is not a duplicate or related to [this one](https://github.com/JesusFreke/fusionIdea/issues/7)

**Comment by JesusFreke** [comment] 2022-06-05 13:54
Hmm. I don't think I've run into that. But I think I do have some pending fixes that I never got around to pushing. I'll check that today and get those pushed and released, and then let's see if it works for you with the new version.

**Comment by Bonjour123** [comment] 2022-06-06 11:26
Ok thank you !
I'll let you know if it get fixed

**Comment by JesusFreke** [comment] 2022-06-07 04:37
I just looked at the pending changes I made, and it won't have any effect on the behavior you're seeing.

I just tried that myself and can reproduce the issue. I've actually ran into that before and tried to figure out what was causing it, but haven't had any success. I think it's probably something deep in the bowels of the integration of pydevd and IDEA/PyCharm. 

You should still be able to debug though. Just resume execution from that initial breakpoint, and it should continue as normal.

**Comment by Bonjour123** [comment] 2022-10-26 07:42
So I've just ignored this bug untill now, when it really bothered me. I might have actually found the trick.
Copy ``C:\Users\[USER]\AppData\Roaming\JetBrains\PyCharm2022.1\plugins\fusion_idea\lib\pydevd-1.9.0\pydevd_attach_to_process\attach_script.py`` to the location of fusion_idea_addin
This allows us to make a relative import of it inside ``fusion_idea_addin.py`` by replacing ``import attach_script`` by ``from . import attach_script``


Relative imports are important because otherwise the imported modules won't be reloaded inside Fusion360 python interpreter, and you would have to restart Fusion360 to see the changes in the imported modules.

Then, still in ``fusion_idea_addin.py``, inside the ``attach`` function, replace the call to pydevd.settrace by:

        pydevd.settrace(
                port=port,
                host=host,
                stdoutToServer=True,
                stderrToServer=True,
                overwrite_prev_trace=True,
                suspend=True,
                trace_only_current_thread=False,
                patch_multiprocessing=False,
                stop_at_frame = False
            )

Notice the ``suspend=True,`` and ``stop_at_frame = False``

While this is the only way I found to make it NOT stop inside ``attach_script.py``, this is completely incoherent with the [settrace sources](https://github.com/fabioz/PyDev.Debugger/blob/main/pydevd.py):
suspend=True is supposed to actually simulate a breakpoint on settrace call, whereas the contrary happens

and stop_at_frame's default is supposed to be False, whereas explicitly setting it as False changes the function's behavior).

**Comment by JesusFreke** [comment] 2022-10-26 17:47
Hmm. Do relative imports cause the module to be reloaded? I don't *think* that's the case? But I could be wrong. I do jump through some hoops elsewhere to ensure, e.g. the script module is reloaded.

But in any case, I'll give it a shot, and merge it in if it looks like it fixes the issue.

Thanks for investigating!

**Comment by JesusFreke** [comment] 2023-03-19 02:57
This should be fixed by 836187ac15c4696dc717a7cb4287b06591a1d321. Thanks for digging into it and suggesting the fix!

**Closed as completed by JesusFreke** 2023-03-19 02:57 UTC
